# Generated by Django 4.1.3 on 2022-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForcesApp', '0002_colector_datos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colector_datos',
            name='dato',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='colector_datos',
            name='fecha',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colector_datos',
            name='tiempo',
            field=models.FloatField(),
        ),
    ]
